const teams = [
    // SÉRIE A
    { id: 1, name: "Palmeiras", short: "PAL", color: "#006437", strength: 93, serie: "A" },
    { id: 2, name: "São Paulo", short: "SAO", color: "#FE0000", strength: 83, serie: "A" },
    { id: 3, name: "Fluminense", short: "FLU", color: "#800020", strength: 84, serie: "A" },
    { id: 4, name: "Bahia", short: "BAH", color: "#005CAB", strength: 85, serie: "A" },
    { id: 5, name: "Flamengo", short: "FLA", color: "#C40000", strength: 94, serie: "A" },
    { id: 6, name: "Coritiba", short: "CFC", color: "#008000", strength: 79, serie: "A" },
    { id: 7, name: "Grêmio", short: "GRE", color: "#00AEEF", strength: 82, serie: "A" },
    { id: 8, name: "Athletico-PR", short: "CAP", color: "#DB0007", strength: 80, serie: "A" },
    { id: 9, name: "Corinthians", short: "COR", color: "#000000", strength: 83, serie: "A" },
    { id: 10, name: "Vasco da Gama", short: "VAS", color: "#000000", strength: 82, serie: "A" },
    { id: 11, name: "Atlético-MG", short: "CAM", color: "#000000", strength: 84, serie: "A" },
    { id: 12, name: "Bragantino", short: "BGT", color: "#FFFFFF", strength: 82, serie: "A" },
    { id: 13, name: "EC Vitória", short: "VIT", color: "#FF0000", strength: 77, serie: "A" },
    { id: 14, name: "Chapecoense", short: "CHA", color: "#008000", strength: 75, serie: "A" },
    { id: 15, name: "Botafogo", short: "BOT", color: "#000000", strength: 88, serie: "A" },
    { id: 16, name: "Mirassol", short: "MIR", color: "#FFFF00", strength: 82, serie: "A" },
    { id: 17, name: "Santos", short: "SAN", color: "#000000", strength: 82, serie: "A" },
    { id: 18, name: "Internacional", short: "INT", color: "#E30613", strength: 83, serie: "A" },
    { id: 19, name: "Cruzeiro", short: "CRU", color: "#0033A0", strength: 84, serie: "A" },
    { id: 20, name: "Remo", short: "REM", color: "#000080", strength: 74, serie: "A" },
    
    // SÉRIE B 
    { id: 21, name: "Fortaleza", short: "FOR", color: "#174594", strength: 84, serie: "B" },
    { id: 22, name: "Ceará", short: "CEA", color: "#000000", strength: 79, serie: "B" },
    { id: 23, name: "Sport", short: "SPT", color: "#D2151E", strength: 77, serie: "B" },
    { id: 24, name: "Goiás", short: "GOI", color: "#006437", strength: 77, serie: "B" },
    { id: 25, name: "Cuiabá", short: "CUI", color: "#006437", strength: 78, serie: "B" },
    { id: 26, name: "Juventude", short: "JUV", color: "#008000", strength: 75, serie: "B" },
    { id: 27, name: "Atlético-GO", short: "ACG", color: "#E30613", strength: 74, serie: "B" },
    { id: 28, name: "Criciúma", short: "CRI", color: "#F7E01A", strength: 76, serie: "B" },
    { id: 29, name: "Novorizontino", short: "NOV", color: "#FFFF00", strength: 79, serie: "B" },
    { id: 30, name: "América-MG", short: "AMG", color: "#008000", strength: 75, serie: "B" },
    { id: 31, name: "Avaí", short: "AVA", color: "#0067B1", strength: 73, serie: "B" },
    { id: 32, name: "CRB", short: "CRB", color: "#FF0000", strength: 72, serie: "B" },
    { id: 33, name: "Vila Nova", short: "VIL", color: "#FF0000", strength: 75, serie: "B" },
    { id: 34, name: "Ponte Preta", short: "PON", color: "#FFFFFF", strength: 73, serie: "B" },
    { id: 35, name: "Operário-PR", short: "OPE", color: "#000000", strength: 76, serie: "B" },
    { id: 36, name: "Londrina", short: "LEC", color: "#00AEEF", strength: 68, serie: "B" },
    { id: 37, name: "Náutico", short: "NAU", color: "#FF0000", strength: 69, serie: "B" },
    { id: 38, name: "São Bernardo", short: "SBE", color: "#FFFF00", strength: 70, serie: "B" },
    { id: 39, name: "Botafogo-SP", short: "BSP", color: "#FF0000", strength: 72, serie: "B" },
    { id: 40, name: "Athletic Club", short: "ATH", color: "#000000", strength: 70, serie: "B" }
];

export default teams;
