const teams = [
    {
        id: 1,
        name: "Palmeiras",
        short: "PAL",
        color: "#006437",
        strength: 93,
        serie: "A",
        budget: 218000000,
        roster: [
            { "pos": "GOL", "name": "Carlos Miguel", "strength": 85, "status": "Titular" },
            { "pos": "LD", "name": "Agustín Giay", "strength": 86, "status": "Titular" },
            { "pos": "ZAG", "name": "Gustavo Gómez", "strength": 89, "status": "Titular" },
            { "pos": "ZAG", "name": "Murilo", "strength": 88, "status": "Titular" },
            { "pos": "LE", "name": "Piquerez", "strength": 87, "status": "Titular" },
            { "pos": "VOL", "name": "Andreas Pereira", "strength": 90, "status": "Titular" },
            { "pos": "VOL", "name": "Richard Ríos", "strength": 86, "status": "Titular" },
            { "pos": "MEI", "name": "Maurício", "strength": 88, "status": "Titular" },
            { "pos": "ATA", "name": "Jhon Arias", "strength": 88, "status": "Titular" },
            { "pos": "ATA", "name": "Gabriel Jesus", "strength": 92, "status": "Titular" },
            { "pos": "CA", "name": "Vitor Roque", "strength": 91, "status": "Titular" },
            { "pos": "GOL", "name": "Weverton", "strength": 85, "status": "Reserva" },
            { "pos": "VOL", "name": "Allan", "strength": 84, "status": "Reserva" },
            { "pos": "MEI", "name": "Raphael Veiga", "strength": 89, "status": "Reserva" },
            { "pos": "ATA", "name": "Estêvão", "strength": 90, "status": "Reserva" }
        ]
    },
    {
        id: 2,
        name: "São Paulo",
        short: "SAO",
        color: "#FE0000",
        strength: 83,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Rafael", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Igor Vinícius", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Arboleda", "strength": 83, "status": "Titular" },
            { "pos": "ZAG", "name": "Alan Franco", "strength": 83, "status": "Titular" },
            { "pos": "ZAG", "name": "Matheus Dória", "strength": 84, "status": "Titular" },
            { "pos": "LE", "name": "Wendell", "strength": 85, "status": "Titular" },
            { "pos": "VOL", "name": "Pablo Maia", "strength": 86, "status": "Titular" },
            { "pos": "VOL", "name": "Marcos Antônio", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Moura", "strength": 87, "status": "Titular" },
            { "pos": "CA", "name": "Calleri", "strength": 86, "status": "Titular" },
            { "pos": "ATA", "name": "Ferreirinha", "strength": 83, "status": "Titular" },
            { "pos": "GOL", "name": "Jandrei", "strength": 77, "status": "Reserva" },
            { "pos": "MEI", "name": "Rodrigo Nestor", "strength": 83, "status": "Reserva" },
            { "pos": "ATA", "name": "Luciano", "strength": 82, "status": "Reserva" }
        ]
    },
    {
        id: 3,
        name: "Fluminense",
        short: "FLU",
        color: "#8A1538",
        strength: 84,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Fábio", "strength": 81, "status": "Titular" },
            { "pos": "LD", "name": "Samuel Xavier", "strength": 80, "status": "Titular" },
            { "pos": "ZAG", "name": "Thiago Silva", "strength": 85, "status": "Titular" },
            { "pos": "LE", "name": "Guilherme Arana", "strength": 88, "status": "Titular" },
            { "pos": "VOL", "name": "Martinelli", "strength": 85, "status": "Titular" },
            { "pos": "VOL", "name": "Hércules", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "Ganso", "strength": 83, "status": "Titular" },
            { "pos": "ATA", "name": "Jefferson Savarino", "strength": 86, "status": "Titular" },
            { "pos": "CA", "name": "Kauã Elias", "strength": 87, "status": "Titular" },
            { "pos": "CA", "name": "Germán Cano", "strength": 82, "status": "Titular" },
            { "pos": "GOL", "name": "Vitor Eudes", "strength": 78, "status": "Reserva" },
            { "pos": "MEI", "name": "Terans", "strength": 80, "status": "Reserva" }
        ]
    },
    {
        id: 4,
        name: "Bahia",
        short: "BAH",
        color: "#0033A0",
        strength: 85,
        serie: "A",
        budget: 82000000,
        roster: [
            { "pos": "GOL", "name": "Marcos Felipe", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Santiago Arias", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Gabriel Xavier", "strength": 87, "status": "Titular" },
            { "pos": "ZAG", "name": "Kanu", "strength": 84, "status": "Titular" },
            { "pos": "LE", "name": "Luciano Juba", "strength": 85, "status": "Titular" },
            { "pos": "VOL", "name": "Caio Alexandre", "strength": 87, "status": "Titular" },
            { "pos": "VOL", "name": "Jean Lucas", "strength": 86, "status": "Titular" },
            { "pos": "MEI", "name": "Cauly", "strength": 88, "status": "Titular" },
            { "pos": "MEI", "name": "Rodrigo Nestor", "strength": 85, "status": "Titular" },
            { "pos": "ATA", "name": "Erick Pulga", "strength": 86, "status": "Titular" },
            { "pos": "CA", "name": "Lucho Rodríguez", "strength": 86, "status": "Titular" },
            { "pos": "ATA", "name": "Ruan Pablo", "strength": 84, "status": "Reserva" }
        ]
    },
    {
        id: 5,
        name: "Flamengo",
        short: "FLA",
        color: "#C40000",
        strength: 96,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Rossi", "strength": 90, "status": "Titular" },
            { "pos": "LD", "name": "Ayrton Lucas", "strength": 88, "status": "Titular" },
            { "pos": "ZAG", "name": "Vitão", "strength": 88, "status": "Titular" },
            { "pos": "ZAG", "name": "Léo Ortiz", "strength": 92, "status": "Titular" },
            { "pos": "VOL", "name": "Gerson", "strength": 91, "status": "Titular" },
            { "pos": "VOL", "name": "De La Cruz", "strength": 92, "status": "Titular" },
            { "pos": "MEI", "name": "Arrascaeta", "strength": 92, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Paquetá", "strength": 94, "status": "Titular" },
            { "pos": "ATA", "name": "Gonzalo Plata", "strength": 88, "status": "Titular" },
            { "pos": "CA", "name": "Pedro", "strength": 93, "status": "Titular" },
            { "pos": "GOL", "name": "Matheus Cunha", "strength": 83, "status": "Reserva" },
            { "pos": "ZAG", "name": "Fabrício Bruno", "strength": 89, "status": "Reserva" },
            { "pos": "ATA", "name": "Everton Cebolinha", "strength": 87, "status": "Reserva" }
        ]
    },
    {
        id: 6,
        name: "Coritiba",
        short: "CFC",
        color: "#006437",
        strength: 79,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Pedro Morisco", "strength": 81, "status": "Titular" },
            { "pos": "LD", "name": "JP Chermont", "strength": 80, "status": "Titular" },
            { "pos": "ZAG", "name": "Thalisson", "strength": 79, "status": "Titular" },
            { "pos": "LE", "name": "Jamerson", "strength": 78, "status": "Titular" },
            { "pos": "VOL", "name": "Sebastián Gómez", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Joaquim Lavega", "strength": 81, "status": "Titular" },
            { "pos": "MEI", "name": "Matheus Frizzo", "strength": 80, "status": "Titular" },
            { "pos": "ATA", "name": "Lucas Ronier", "strength": 83, "status": "Titular" },
            { "pos": "ATA", "name": "Breno Lopes", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Robson", "strength": 79, "status": "Titular" },
            { "pos": "CA", "name": "Eberth", "strength": 78, "status": "Titular" }
        ]
    },
    {
        id: 7,
        name: "Grêmio",
        short: "GRE",
        color: "#0099FF",
        strength: 82,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Marchesín", "strength": 83, "status": "Titular" },
            { "pos": "LD", "name": "João Pedro", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Juan Nardoni", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Kannemann", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Villasanti", "strength": 85, "status": "Titular" },
            { "pos": "VOL", "name": "Arthur Melo", "strength": 86, "status": "Titular" },
            { "pos": "MEI", "name": "Franco Cristaldo", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "Gabriel Mec", "strength": 85, "status": "Titular" },
            { "pos": "ATA", "name": "Tetê", "strength": 87, "status": "Titular" },
            { "pos": "ATA", "name": "Monsalve", "strength": 82, "status": "Titular" },
            { "pos": "CA", "name": "Martin Braithwaite", "strength": 83, "status": "Titular" }
        ]
    },
    {
        id: 8,
        name: "Athletico-PR",
        short: "CAP",
        color: "#CC0000",
        strength: 80,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Mycael", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Leo Godoy", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Kaique Rocha", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Mateo Gamarra", "strength": 80, "status": "Titular" },
            { "pos": "LE", "name": "Lucas Esquivel", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Felipinho", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Juan Portilla", "strength": 83, "status": "Titular" },
            { "pos": "MEI", "name": "Bruno Zapelli", "strength": 85, "status": "Titular" },
            { "pos": "ATA", "name": "Canobbio", "strength": 82, "status": "Titular" },
            { "pos": "CA", "name": "Kevin Viveros", "strength": 82, "status": "Titular" },
            { "pos": "ATA", "name": "Pablo", "strength": 78, "status": "Reserva" }
        ]
    },
    {
        id: 9,
        name: "Corinthians",
        short: "COR",
        color: "#FFFFFF",
        strength: 83,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Matheus Donelli", "strength": 81, "status": "Titular" },
            { "pos": "LD", "name": "Matheuzinho", "strength": 83, "status": "Titular" },
            { "pos": "ZAG", "name": "André", "strength": 85, "status": "Titular" },
            { "pos": "ZAG", "name": "Gustavo Henrique", "strength": 83, "status": "Titular" },
            { "pos": "LE", "name": "Matheus Bidu", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Breno Bidon", "strength": 85, "status": "Titular" },
            { "pos": "VOL", "name": "Raniele", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "Rodrigo Garro", "strength": 89, "status": "Titular" },
            { "pos": "ATA", "name": "Memphis Depay", "strength": 89, "status": "Titular" },
            { "pos": "CA", "name": "Yuri Alberto", "strength": 87, "status": "Titular" },
            { "pos": "ATA", "name": "Kaio César", "strength": 82, "status": "Reserva" }
        ]
    },
    {
        id: 10,
        name: "Vasco da Gama",
        short: "VAS",
        color: "#000000",
        strength: 82,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Léo Jardim", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Paulo Henrique", "strength": 80, "status": "Titular" },
            { "pos": "ZAG", "name": "João Victor", "strength": 83, "status": "Titular" },
            { "pos": "ZAG", "name": "Robert Renan", "strength": 85, "status": "Titular" },
            { "pos": "ZAG", "name": "Carlos Cuesta", "strength": 84, "status": "Titular" },
            { "pos": "LE", "name": "Lucas Piton", "strength": 84, "status": "Titular" },
            { "pos": "LE", "name": "Cuiabano", "strength": 83, "status": "Titular" },
            { "pos": "VOL", "name": "Mateus Carvalho", "strength": 82, "status": "Titular" },
            { "pos": "MEI", "name": "Philippe Coutinho", "strength": 84, "status": "Titular" },
            { "pos": "ATA", "name": "Andrés Gómez", "strength": 86, "status": "Titular" },
            { "pos": "CA", "name": "Vegetti", "strength": 82, "status": "Titular" }
        ]
    },
    {
        id: 11,
        name: "Atlético-MG",
        short: "CAM",
        color: "#000000",
        strength: 84,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Everson", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Renzo Saravia", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Junior Alonso", "strength": 85, "status": "Titular" },
            { "pos": "LE", "name": "Renan Lodi", "strength": 86, "status": "Titular" },
            { "pos": "VOL", "name": "Alexsander", "strength": 86, "status": "Titular" },
            { "pos": "VOL", "name": "Alan Franco", "strength": 81, "status": "Titular" },
            { "pos": "MEI", "name": "Gustavo Scarpa", "strength": 87, "status": "Titular" },
            { "pos": "MEI", "name": "Victor Hugo", "strength": 84, "status": "Titular" },
            { "pos": "ATA", "name": "Paulinho", "strength": 88, "status": "Titular" },
            { "pos": "CA", "name": "Hulk", "strength": 88, "status": "Titular" },
            { "pos": "ZAG", "name": "Lyanco", "strength": 84, "status": "Reserva" }
        ]
    },
    {
        id: 12,
        name: "Bragantino",
        short: "RBB",
        color: "#FFFFFF",
        strength: 82,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Cleiton", "strength": 82, "status": "Titular" },
            { "pos": "LD", "name": "Andrés Hurtado", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Guzmán Rodríguez", "strength": 81, "status": "Titular" },
            { "pos": "LE", "name": "Juninho Capixaba", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Ignacio Sosa", "strength": 81, "status": "Titular" },
            { "pos": "MEI", "name": "Rodriguinho", "strength": 80, "status": "Titular" },
            { "pos": "ATA", "name": "Lucas Barbosa", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Henry Mosquera", "strength": 80, "status": "Titular" },
            { "pos": "CA", "name": "Isidro Pitta", "strength": 82, "status": "Titular" }
        ]
    },
    {
        id: 13,
        name: "EC Vitória",
        short: "VIT",
        color: "#D80027",
        strength: 77,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Lucas Arcanjo", "strength": 79, "status": "Titular" },
            { "pos": "LD", "name": "Willean Lepo", "strength": 76, "status": "Titular" },
            { "pos": "ZAG", "name": "Riccieli", "strength": 80, "status": "Titular" },
            { "pos": "ZAG", "name": "Wagner Leonardo", "strength": 80, "status": "Titular" },
            { "pos": "LE", "name": "Luan Cândido", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Willian Oliveira", "strength": 76, "status": "Titular" },
            { "pos": "MEI", "name": "Matheusinho", "strength": 80, "status": "Titular" },
            { "pos": "ATA", "name": "Aitor Cantalapiedra", "strength": 82, "status": "Titular" },
            { "pos": "CA", "name": "Alerrandro", "strength": 78, "status": "Titular" }
        ]
    },
    {
        id: 14,
        name: "Chapecoense",
        short: "CHA",
        color: "#00913F",
        strength: 75,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Anderson", "strength": 80, "status": "Titular" },
            { "pos": "LD", "name": "Marcelinho", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": "Rafael Thyere", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Bruno Leonardo", "strength": 77, "status": "Titular" },
            { "pos": "LE", "name": "Mancha", "strength": 75, "status": "Titular" },
            { "pos": "VOL", "name": "Camilo", "strength": 78, "status": "Titular" },
            { "pos": "MEI", "name": "Robert Santos", "strength": 77, "status": "Titular" },
            { "pos": "ATA", "name": "Maurício Garcez", "strength": 79, "status": "Titular" },
            { "pos": "CA", "name": "Perotti", "strength": 78, "status": "Titular" }
        ]
    },
    {
        id: 15,
        name: "Botafogo",
        short: "BOT",
        color: "#000000",
        strength: 88,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "John", "strength": 88, "status": "Titular" },
            { "pos": "LD", "name": "Danilo", "strength": 87, "status": "Titular" },
            { "pos": "ZAG", "name": "Alexander Barboza", "strength": 88, "status": "Titular" },
            { "pos": "MEI", "name": "Cristian Medina", "strength": 86, "status": "Titular" },
            { "pos": "MEI", "name": "Álvaro Montoro", "strength": 83, "status": "Titular" },
            { "pos": "MEI", "name": "Thiago Almada", "strength": 92, "status": "Titular" },
            { "pos": "ATA", "name": "Luiz Henrique", "strength": 93, "status": "Titular" },
            { "pos": "ATA", "name": "Artur", "strength": 86, "status": "Titular" },
            { "pos": "ATA", "name": "Matheus Martins", "strength": 87, "status": "Titular" },
            { "pos": "CA", "name": "Igor Jesus", "strength": 91, "status": "Titular" },
            { "pos": "CA", "name": "Tiquinho Soares", "strength": 84, "status": "Reserva" }
        ]
    },
    {
        id: 16,
        name: "Mirassol",
        short: "MIR",
        color: "#FFD700",
        strength: 82,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Alex Muralha", "strength": 80, "status": "Titular" },
            { "pos": "LD", "name": "Antonio Galeano", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Willian Machado", "strength": 78, "status": "Titular" },
            { "pos": "LE", "name": "Zeca", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Danielzinho", "strength": 83, "status": "Titular" },
            { "pos": "MEI", "name": "Shaylon", "strength": 85, "status": "Titular" },
            { "pos": "ATA", "name": "Negueba", "strength": 80, "status": "Titular" },
            { "pos": "CA", "name": "Dellatorre", "strength": 82, "status": "Titular" }
        ]
    },
    {
        id: 17,
        name: "Santos",
        short: "SAN",
        color: "#FFFFFF",
        strength: 82,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Gabriel Brazão", "strength": 87, "status": "Titular" },
            { "pos": "LD", "name": "Mayke", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Lucas Veríssimo", "strength": 86, "status": "Titular" },
            { "pos": "LE", "name": "Vinicius Lira", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Gabriel Menino", "strength": 86, "status": "Titular" },
            { "pos": "MEI", "name": "Benjamín Rollheiser", "strength": 85, "status": "Titular" },
            { "pos": "MEI", "name": "Neymar", "strength": 98, "status": "Titular" },
            { "pos": "ATA", "name": "Álvaro Barreal", "strength": 86, "status": "Titular" },
            { "pos": "CA", "name": "Gabigol", "strength": 90, "status": "Titular" },
            { "pos": "GOL", "name": "Diógenes", "strength": 78, "status": "Reserva" }
        ]
    },
    {
        id: 18,
        name: "Internacional",
        short: "INT",
        color: "#E50000",
        strength: 83,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Sergio Rochet", "strength": 87, "status": "Titular" },
            { "pos": "LD", "name": "Rodrigo Villagra", "strength": 83, "status": "Titular" },
            { "pos": "ZAG", "name": "Vitão", "strength": 85, "status": "Titular" },
            { "pos": "LE", "name": "Bernabei", "strength": 85, "status": "Titular" },
            { "pos": "VOL", "name": "Thiago Maia", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "Alan Patrick", "strength": 86, "status": "Titular" },
            { "pos": "CA", "name": "Rafael Borré", "strength": 86, "status": "Titular" },
            { "pos": "GOL", "name": "Anthoni", "strength": 80, "status": "Reserva" }
        ]
    },
    {
        id: 19,
        name: "Cruzeiro",
        short: "CRU",
        color: "#0000CD",
        strength: 84,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Cássio", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "William", "strength": 85, "status": "Titular" },
            { "pos": "ZAG", "name": "João Marcelo", "strength": 85, "status": "Titular" },
            { "pos": "ZAG", "name": "Fabrício Bruno", "strength": 88, "status": "Titular" },
            { "pos": "LE", "name": "Kaiki Bruno", "strength": 83, "status": "Titular" },
            { "pos": "VOL", "name": "Matheus Henrique", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "Matheus Pereira", "strength": 90, "status": "Titular" },
            { "pos": "ATA", "name": "Kaio Jorge", "strength": 85, "status": "Titular" },
            { "pos": "CA", "name": "Dinenno", "strength": 82, "status": "Titular" }
        ]
    },
    {
        id: 20,
        name: "Remo",
        short: "REM",
        color: "#0B173B",
        strength: 74,
        serie: "A",
        roster: [
            { "pos": "GOL", "name": "Marcelo Rangel", "strength": 74, "status": "Titular" },
            { "pos": "LD", "name": "Thalys", "strength": 73, "status": "Titular" },
            { "pos": "VOL", "name": "Patrick de Paula", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Leonel Picco", "strength": 77, "status": "Titular" },
            { "pos": "MEI", "name": "Vitor Bueno", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Diego Hernández", "strength": 78, "status": "Titular" },
            { "pos": "ATA", "name": "Pedro Vitor", "strength": 75, "status": "Titular" },
            { "pos": "CA", "name": "Ytalo", "strength": 75, "status": "Titular" }
        ]
    },
    // SÉRIE B 
    { 
        id: 21, 
        name: "Fortaleza", 
        short: "FOR", 
        color: "#174594", 
        strength: 84, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "João Ricardo", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Emanuel Britez", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Lucas Gazal", "strength": 80, "status": "Titular" },
            { "pos": "ZAG", "name": "Arthur Barbosa", "strength": 78, "status": "Titular" },
            { "pos": "LE", "name": "Weverson", "strength": 79, "status": "Titular" },
            { "pos": "VOL", "name": "José Welison", "strength": 83, "status": "Titular" },
            { "pos": "VOL", "name": "Lucas Sasha", "strength": 81, "status": "Titular" },
            { "pos": "MEI", "name": "Tomás Pochettino", "strength": 85, "status": "Titular" },
            { "pos": "MEI", "name": "Yago Pikachu", "strength": 84, "status": "Titular" },
            { "pos": "ATA", "name": "Marinho", "strength": 82, "status": "Titular" },
            { "pos": "CA", "name": "Juan Martín Lucero", "strength": 86, "status": "Titular" },
            { "pos": "GOL", "name": "Helton Leite", "strength": 78, "status": "Reserva" },
            { "pos": "MEI", "name": "Emmanuel Martínez", "strength": 81, "status": "Reserva" },
            { "pos": "MEI", "name": "Matheus Rossetto", "strength": 79, "status": "Reserva" },
            { "pos": "ATA", "name": "Deyverson", "strength": 81, "status": "Reserva" }
        ]
    },
    { 
        id: 22, 
        name: "Ceará", 
        short: "CEA", 
        color: "#000000", 
        strength: 79, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Richard", "strength": 79, "status": "Titular" },
            { "pos": "LD", "name": "Rafael Ramos", "strength": 77, "status": "Titular" },
            { "pos": "ZAG", "name": "Marllon", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Luiz Otávio", "strength": 80, "status": "Titular" },
            { "pos": "LE", "name": "Matheus Bahia", "strength": 77, "status": "Titular" },
            { "pos": "VOL", "name": "Richardson", "strength": 76, "status": "Titular" },
            { "pos": "VOL", "name": "Lourenço", "strength": 77, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Mugni", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Lima", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Saulo Mineiro", "strength": 78, "status": "Titular" },
            { "pos": "CA", "name": "Pedro Raúl", "strength": 80, "status": "Titular" },
            { "pos": "GOL", "name": "Keiller", "strength": 76, "status": "Reserva" },
            { "pos": "MEI", "name": "Rodriguinho", "strength": 75, "status": "Reserva" },
            { "pos": "ATA", "name": "Paulo Baya", "strength": 76, "status": "Reserva" }
        ]
    },
    { 
        id: 23, 
        name: "Sport", 
        short: "SPT", 
        color: "#D2151E", 
        strength: 77, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Caíque", "strength": 76, "status": "Titular" },
            { "pos": "LD", "name": "Rafinha", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": "Alisson Cassiano", "strength": 77, "status": "Titular" },
            { "pos": "ZAG", "name": "Renzo", "strength": 75, "status": "Titular" },
            { "pos": "LE", "name": "Kevyson", "strength": 74, "status": "Titular" },
            { "pos": "VOL", "name": "Christian Rivera", "strength": 77, "status": "Titular" },
            { "pos": "VOL", "name": "Lucas Kal", "strength": 76, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Lima", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Hyoran", "strength": 78, "status": "Titular" },
            { "pos": "ATA", "name": "Romarinho", "strength": 77, "status": "Titular" },
            { "pos": "CA", "name": "Zé Roberto", "strength": 78, "status": "Titular" },
            { "pos": "GOL", "name": "Thiago Couto", "strength": 74, "status": "Reserva" },
            { "pos": "ATA", "name": "Derik Lacerda", "strength": 75, "status": "Reserva" },
            { "pos": "CA", "name": "Gonçalo Paciência", "strength": 76, "status": "Reserva" }
        ]
    },
    { 
        id: 24, 
        name: "Goiás", 
        short: "GOI", 
        color: "#006437", 
        strength: 77, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Tadeu", "strength": 82, "status": "Titular" },
            { "pos": "LD", "name": "Diego Sousa", "strength": 75, "status": "Titular" },
            { "pos": "ZAG", "name": "Messias", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Rodrigo", "strength": 76, "status": "Titular" },
            { "pos": "LE", "name": "Sander", "strength": 77, "status": "Titular" },
            { "pos": "VOL", "name": "Machado", "strength": 76, "status": "Titular" },
            { "pos": "VOL", "name": "Juninho", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Lima", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Gegê", "strength": 77, "status": "Titular" },
            { "pos": "ATA", "name": "Bruno Sávio", "strength": 77, "status": "Titular" },
            { "pos": "CA", "name": "Anselmo Ramon", "strength": 79, "status": "Titular" },
            { "pos": "GOL", "name": "Thiago Rodrigues", "strength": 74, "status": "Reserva" },
            { "pos": "MEI", "name": "Jean Carlos", "strength": 76, "status": "Reserva" },
            { "pos": "ATA", "name": "Wellinton Rato", "strength": 78, "status": "Reserva" }
        ]
    },
    { 
        id: 25, 
        name: "Cuiabá", 
        short: "CUI", 
        color: "#006437", 
        strength: 78, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Walter", "strength": 80, "status": "Titular" },
            { "pos": "LD", "name": "Railan", "strength": 75, "status": "Titular" },
            { "pos": "ZAG", "name": "Marllon", "strength": 77, "status": "Titular" },
            { "pos": "ZAG", "name": "Bruno Alves", "strength": 78, "status": "Titular" },
            { "pos": "LE", "name": "Ramon", "strength": 76, "status": "Titular" },
            { "pos": "VOL", "name": "Lucas Mineiro", "strength": 77, "status": "Titular" },
            { "pos": "VOL", "name": "Fernando Sobral", "strength": 78, "status": "Titular" },
            { "pos": "MEI", "name": "Max", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Denilson", "strength": 77, "status": "Titular" },
            { "pos": "ATA", "name": "Clayson", "strength": 78, "status": "Titular" },
            { "pos": "CA", "name": "Isidro Pitta", "strength": 81, "status": "Titular" },
            { "pos": "GOL", "name": "Mateus Pasinato", "strength": 74, "status": "Reserva" },
            { "pos": "ATA", "name": "Derik Lacerda", "strength": 75, "status": "Reserva" },
            { "pos": "CA", "name": "Deyverson", "strength": 79, "status": "Reserva" }
        ]
    },
    {
        id: 26,
        name: "Juventude",
        short: "JUV",
        color: "#008000",
        strength: 75,
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Jandrei", "strength": 76, "status": "Titular" },
            { "pos": "LD", "name": "Reginaldo", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": "Rodrigo Sam", "strength": 75, "status": "Titular" },
            { "pos": "ZAG", "name": "Wilker Ángel", "strength": 77, "status": "Titular" },
            { "pos": "LE", "name": "Alan Ruschel", "strength": 76, "status": "Titular" },
            { "pos": "VOL", "name": "Jádson", "strength": 75, "status": "Titular" },
            { "pos": "VOL", "name": "Juan Sforza", "strength": 78, "status": "Titular" },
            { "pos": "MEI", "name": "Nenê", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Fernandes", "strength": 77, "status": "Titular" },
            { "pos": "ATA", "name": "Gabriel Veron", "strength": 78, "status": "Titular" },
            { "pos": "CA", "name": "Gilberto", "strength": 79, "status": "Titular" },
            { "pos": "GOL", "name": "Marcos Miranda", "strength": 74, "status": "Reserva" },
            { "pos": "LE", "name": "Marcelo Hermes", "strength": 75, "status": "Reserva" },
            { "pos": "ATA", "name": "Giovanny", "strength": 74, "status": "Reserva" }
        ]
    },
    {
        id: 27,
        name: "Atlético-GO",
        short: "ACG",
        color: "#E30613",
        strength: 74,
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Ronaldo", "strength": 76, "status": "Titular" },
            { "pos": "LD", "name": "Maguinho", "strength": 73, "status": "Titular" },
            { "pos": "ZAG", "name": "Adriano Martins", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": "Alix Vinícius", "strength": 75, "status": "Titular" },
            { "pos": "LE", "name": "Guilherme Romão", "strength": 74, "status": "Titular" },
            { "pos": "VOL", "name": "Gabriel Baralhas", "strength": 77, "status": "Titular" },
            { "pos": "VOL", "name": "Rhaldney", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Shaylon", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Jorginho", "strength": 77, "status": "Titular" },
            { "pos": "ATA", "name": "Luiz Fernando", "strength": 79, "status": "Titular" },
            { "pos": "CA", "name": "Derek", "strength": 76, "status": "Titular" },
            { "pos": "GOL", "name": "Pedro Rangel", "strength": 73, "status": "Reserva" },
            { "pos": "VOL", "name": "Roni", "strength": 75, "status": "Reserva" },
            { "pos": "CA", "name": "Emiliano Rodríguez", "strength": 74, "status": "Reserva" }
        ]
    },
    {
        id: 28,
        name: "Criciúma",
        short: "CRI",
        color: "#F7E01A",
        strength: 76,
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Gustavo", "strength": 78, "status": "Titular" },
            { "pos": "LD", "name": "Claudinho", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": "Rodrigo", "strength": 76, "status": "Titular" },
            { "pos": "ZAG", "name": "Tobias Figueiredo", "strength": 77, "status": "Titular" },
            { "pos": "LE", "name": "Marcelo Hermes", "strength": 75, "status": "Titular" },
            { "pos": "VOL", "name": "Barreto", "strength": 76, "status": "Titular" },
            { "pos": "VOL", "name": "Higor Meritão", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Marquinhos Gabriel", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Fellipe Mateus", "strength": 77, "status": "Titular" },
            { "pos": "ATA", "name": "Arthur Caíke", "strength": 76, "status": "Titular" },
            { "pos": "CA", "name": "Yannick Bolasie", "strength": 82, "status": "Titular" },
            { "pos": "GOL", "name": "Matheus Cavichioli", "strength": 75, "status": "Reserva" },
            { "pos": "CA", "name": "Felipe Vizeu", "strength": 76, "status": "Reserva" },
            { "pos": "CA", "name": "Éder", "strength": 75, "status": "Reserva" }
        ]
    },
    {
        id: 29,
        name: "Novorizontino",
        short: "NOV",
        color: "#FFFF00",
        strength: 74,
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Jordi", "strength": 77, "status": "Titular" },
            { "pos": "LD", "name": "Raul Prata", "strength": 73, "status": "Titular" },
            { "pos": "ZAG", "name": "César Martins", "strength": 75, "status": "Titular" },
            { "pos": "ZAG", "name": "Rafael Donato", "strength": 76, "status": "Titular" },
            { "pos": "LE", "name": "Reinaldo", "strength": 74, "status": "Titular" },
            { "pos": "VOL", "name": "Geovane", "strength": 75, "status": "Titular" },
            { "pos": "VOL", "name": "Willian Farias", "strength": 76, "status": "Titular" },
            { "pos": "MEI", "name": "Marlon", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Eduardo", "strength": 74, "status": "Titular" },
            { "pos": "ATA", "name": "Waguininho", "strength": 76, "status": "Titular" },
            { "pos": "CA", "name": "Neto Pessoa", "strength": 77, "status": "Titular" },
            { "pos": "GOL", "name": "Lucas", "strength": 72, "status": "Reserva" },
            { "pos": "CA", "name": "Lucca", "strength": 75, "status": "Reserva" },
            { "pos": "CA", "name": "Rodolfo", "strength": 73, "status": "Reserva" }
        ]
    },
    {
        id: 30,
        name: "América-MG",
        short: "AMG",
        color: "#008000",
        strength: 75,
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Cássio", "strength": 78, "status": "Titular" },
            { "pos": "LD", "name": "Daniel Borges", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": "Éder", "strength": 76, "status": "Titular" },
            { "pos": "ZAG", "name": "Ricardo Silva", "strength": 75, "status": "Titular" },
            { "pos": "LE", "name": "Nicolas", "strength": 74, "status": "Titular" },
            { "pos": "VOL", "name": "Juninho", "strength": 79, "status": "Titular" },
            { "pos": "VOL", "name": "Alê", "strength": 76, "status": "Titular" },
            { "pos": "MEI", "name": "Benítez", "strength": 81, "status": "Titular" },
            { "pos": "MEI", "name": "Moisés", "strength": 77, "status": "Titular" },
            { "pos": "ATA", "name": "Fabinho", "strength": 75, "status": "Titular" },
            { "pos": "CA", "name": "Renato Marques", "strength": 76, "status": "Titular" },
            { "pos": "GOL", "name": "Gustavo", "strength": 73, "status": "Reserva" },
            { "pos": "MEI", "name": "Felipe Amaral", "strength": 74, "status": "Reserva" },
            { "pos": "CA", "name": "Brenner", "strength": 75, "status": "Reserva" }
        ]
    },
    { 
        id: 31, 
        name: "Avaí", 
        short: "AVA", 
        color: "#0067B1", 
        strength: 73, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Igor Bohn", "strength": 75, "status": "Titular" },
            { "pos": "LD", "name": "Wesley", "strength": 72, "status": "Titular" },
            { "pos": "ZAG", "name": "Douglas", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": "Nicolás Cabral", "strength": 73, "status": "Titular" },
            { "pos": "LE", "name": "Mateus Quaresma", "strength": 73, "status": "Titular" },
            { "pos": "VOL", "name": "Wenderson", "strength": 74, "status": "Titular" },
            { "pos": "VOL", "name": "Zé Ricardo", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Daniel Penha", "strength": 78, "status": "Titular" },
            { "pos": "MEI", "name": "Giovanni", "strength": 76, "status": "Titular" },
            { "pos": "ATA", "name": "Pedrinho", "strength": 74, "status": "Titular" },
            { "pos": "CA", "name": "Felipe Avenatti", "strength": 77, "status": "Titular" },
            { "pos": "GOL", "name": "Otávio", "strength": 71, "status": "Reserva" },
            { "pos": "MEI", "name": "Jean Lucas", "strength": 74, "status": "Reserva" },
            { "pos": "ATA", "name": "Bilu", "strength": 73, "status": "Reserva" }
        ]
    },
    { 
        id: 32, 
        name: "CRB", 
        short: "CRB", 
        color: "#FF0000", 
        strength: 72, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Matheus Albino", "strength": 75, "status": "Titular" },
            { "pos": "LD", "name": "Hereda", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": " Henri Santos", "strength": 72, "status": "Titular" },
            { "pos": "ZAG", "name": "Maycon", "strength": 73, "status": "Titular" },
            { "pos": "LE", "name": "Lucas Lovat", "strength": 72, "status": "Titular" },
            { "pos": "VOL", "name": "Geovane", "strength": 73, "status": "Titular" },
            { "pos": "VOL", "name": "Pedro Castro", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Danielzinho", "strength": 77, "status": "Titular" },
            { "pos": "MEI", "name": "Guilherme Estrella", "strength": 74, "status": "Titular" },
            { "pos": "ATA", "name": "Douglas Baggio", "strength": 76, "status": "Titular" },
            { "pos": "CA", "name": "Guilherme Pato", "strength": 75, "status": "Titular" },
            { "pos": "GOL", "name": "Vitor Caetano", "strength": 71, "status": "Reserva" },
            { "pos": "ATA", "name": "Léo Pereira", "strength": 74, "status": "Reserva" },
            { "pos": "CA", "name": "Luiz Phellype", "strength": 73, "status": "Reserva" }
        ]
    },
    { 
        id: 33, 
        name: "Vila Nova", 
        short: "VIL", 
        color: "#FF0000", 
        strength: 75, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Dalberson", "strength": 76, "status": "Titular" },
            { "pos": "LD", "name": "Hayner", "strength": 75, "status": "Titular" },
            { "pos": "ZAG", "name": "Anderson Jesus", "strength": 74, "status": "Titular" },
            { "pos": "ZAG", "name": "Willian Prado", "strength": 73, "status": "Titular" },
            { "pos": "LE", "name": "Tiago", "strength": 72, "status": "Titular" },
            { "pos": "VOL", "name": "Willian Maranhão", "strength": 75, "status": "Titular" },
            { "pos": "VOL", "name": "Dudu", "strength": 76, "status": "Titular" },
            { "pos": "MEI", "name": "Marquinhos Gabriel", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Dodô", "strength": 74, "status": "Titular" },
            { "pos": "ATA", "name": "Janderson", "strength": 76, "status": "Titular" },
            { "pos": "CA", "name": "Dellatorre", "strength": 78, "status": "Titular" },
            { "pos": "GOL", "name": "Helton Leite", "strength": 75, "status": "Reserva" },
            { "pos": "ATA", "name": "André Luis", "strength": 74, "status": "Reserva" },
            { "pos": "CA", "name": "Rafael Silva", "strength": 75, "status": "Reserva" }
        ]
    },
    { 
        id: 34, 
        name: "Ponte Preta", 
        short: "PON", 
        color: "#FFFFFF", 
        strength: 73, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Diogo Silva", "strength": 76, "status": "Titular" },
            { "pos": "LD", "name": "Pacheco", "strength": 72, "status": "Titular" },
            { "pos": "ZAG", "name": "David Braz", "strength": 77, "status": "Titular" },
            { "pos": "ZAG", "name": "Sergio Palacios", "strength": 73, "status": "Titular" },
            { "pos": "LE", "name": "Danilo Barcelos", "strength": 74, "status": "Titular" },
            { "pos": "VOL", "name": "Leo Gomes", "strength": 73, "status": "Titular" },
            { "pos": "VOL", "name": "Rodrigo Saravia", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Élvis", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Diogo Mora", "strength": 72, "status": "Titular" },
            { "pos": "ATA", "name": "William Pottker", "strength": 77, "status": "Titular" },
            { "pos": "CA", "name": "Jonathan Cafu", "strength": 76, "status": "Titular" },
            { "pos": "GOL", "name": "Thiago Coelho", "strength": 73, "status": "Reserva" },
            { "pos": "ATA", "name": "Luis Phelipe", "strength": 74, "status": "Reserva" },
            { "pos": "CA", "name": "David da Hora", "strength": 74, "status": "Reserva" }
        ]
    },
    { 
        id: 35, 
        name: "Operário-PR", 
        short: "OPE", 
        color: "#000000", 
        strength: 76, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Elias Curzel", "strength": 74, "status": "Titular" },
            { "pos": "LD", "name": "Diogo Mateus", "strength": 75, "status": "Titular" },
            { "pos": "ZAG", "name": "Miranda", "strength": 77, "status": "Titular" },
            { "pos": "ZAG", "name": "José Cuenú", "strength": 74, "status": "Titular" },
            { "pos": "LE", "name": "Gabriel Feliciano", "strength": 73, "status": "Titular" },
            { "pos": "VOL", "name": "Índio", "strength": 76, "status": "Titular" },
            { "pos": "VOL", "name": "Matheus Trindade", "strength": 74, "status": "Titular" },
            { "pos": "MEI", "name": "Gabriel Boschilia", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Pedro Vilhena", "strength": 75, "status": "Titular" },
            { "pos": "ATA", "name": "Felipe Augusto", "strength": 76, "status": "Titular" },
            { "pos": "CA", "name": "Vinicius Mingotti", "strength": 77, "status": "Titular" },
            { "pos": "GOL", "name": "Vagner", "strength": 75, "status": "Reserva" },
            { "pos": "MEI", "name": "Juan Zuluaga", "strength": 74, "status": "Reserva" },
            { "pos": "CA", "name": "Ademilson", "strength": 76, "status": "Reserva" }
        ]
    },
    { 
        id: 36, 
        name: "Londrina", 
        short: "LEC", 
        color: "#00AEEF", 
        strength: 68, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Mauricio Kozlinski", "strength": 72, "status": "Titular" },
            { "pos": "LD", "name": "André Dhominique", "strength": 68, "status": "Titular" },
            { "pos": "ZAG", "name": "Gabriel Lacerda", "strength": 70, "status": "Titular" },
            { "pos": "ZAG", "name": "João Maistro", "strength": 69, "status": "Titular" },
            { "pos": "LE", "name": "Kevyn", "strength": 67, "status": "Titular" },
            { "pos": "VOL", "name": "João Tavares", "strength": 68, "status": "Titular" },
            { "pos": "VOL", "name": "André Luiz", "strength": 69, "status": "Titular" },
            { "pos": "MEI", "name": "Nadson", "strength": 71, "status": "Titular" },
            { "pos": "MEI", "name": "Gian Tortorella", "strength": 68, "status": "Titular" },
            { "pos": "ATA", "name": "Iago Teles", "strength": 70, "status": "Titular" },
            { "pos": "CA", "name": "Diego Quirino", "strength": 71, "status": "Titular" },
            { "pos": "GOL", "name": "Gabriel Felix", "strength": 66, "status": "Reserva" },
            { "pos": "ZAG", "name": "Wallace", "strength": 68, "status": "Reserva" },
            { "pos": "CA", "name": "Elias", "strength": 69, "status": "Reserva" }
        ]
    },
    { 
        id: 37, 
        name: "Náutico", 
        short: "NAU", 
        color: "#FF0000", 
        strength: 69, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Gastón Guruceaga", "strength": 72, "status": "Titular" },
            { "pos": "LD", "name": "Arnaldo", "strength": 68, "status": "Titular" },
            { "pos": "ZAG", "name": "Alemão", "strength": 70, "status": "Titular" },
            { "pos": "ZAG", "name": "Mateus Silva", "strength": 71, "status": "Titular" },
            { "pos": "LE", "name": "Luiz Paulo", "strength": 68, "status": "Titular" },
            { "pos": "VOL", "name": "Auremir", "strength": 70, "status": "Titular" },
            { "pos": "VOL", "name": "Leonai", "strength": 69, "status": "Titular" },
            { "pos": "MEI", "name": "Dodô", "strength": 72, "status": "Titular" },
            { "pos": "MEI", "name": "Juninho", "strength": 68, "status": "Titular" },
            { "pos": "ATA", "name": "Vinícius", "strength": 71, "status": "Titular" },
            { "pos": "CA", "name": "Felipe Azevedo", "strength": 73, "status": "Titular" },
            { "pos": "GOL", "name": "Muriel", "strength": 71, "status": "Reserva" },
            { "pos": "MEI", "name": "Vitinho", "strength": 68, "status": "Reserva" },
            { "pos": "ATA", "name": "Jonas Toró", "strength": 70, "status": "Reserva" }
        ]
    },
    { 
        id: 38, 
        name: "São Bernardo", 
        short: "SBE", 
        color: "#FFFF00", 
        strength: 70, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Alex Alves", "strength": 71, "status": "Titular" },
            { "pos": "LD", "name": "Rodrigo Ferreira", "strength": 69, "status": "Titular" },
            { "pos": "ZAG", "name": "Rafael Forster", "strength": 72, "status": "Titular" },
            { "pos": "ZAG", "name": "Hélder Maciel", "strength": 70, "status": "Titular" },
            { "pos": "LE", "name": "Arthur Henrique", "strength": 69, "status": "Titular" },
            { "pos": "VOL", "name": "Rodrigo Souza", "strength": 71, "status": "Titular" },
            { "pos": "VOL", "name": "Emerson Santos", "strength": 70, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Lima", "strength": 73, "status": "Titular" },
            { "pos": "MEI", "name": "Alan Santos", "strength": 71, "status": "Titular" },
            { "pos": "ATA", "name": "Victor Andrade", "strength": 72, "status": "Titular" },
            { "pos": "CA", "name": "Kayke", "strength": 74, "status": "Titular" },
            { "pos": "GOL", "name": "Vanderlei", "strength": 72, "status": "Reserva" },
            { "pos": "ATA", "name": "Echaporã", "strength": 70, "status": "Reserva" },
            { "pos": "CA", "name": "Silvinho", "strength": 71, "status": "Reserva" }
        ]
    },
    { 
        id: 39, 
        name: "Botafogo-SP", 
        short: "BSP", 
        color: "#FF0000", 
        strength: 72, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Victor Souza", "strength": 73, "status": "Titular" },
            { "pos": "LD", "name": "Thassio", "strength": 70, "status": "Titular" },
            { "pos": "ZAG", "name": "Matheus Costa", "strength": 72, "status": "Titular" },
            { "pos": "ZAG", "name": "Bernardo Schappo", "strength": 73, "status": "Titular" },
            { "pos": "LE", "name": "Jean Victor", "strength": 71, "status": "Titular" },
            { "pos": "VOL", "name": "Matheus Sales", "strength": 74, "status": "Titular" },
            { "pos": "VOL", "name": "Everton Morelli", "strength": 72, "status": "Titular" },
            { "pos": "MEI", "name": "Rafael Gava", "strength": 76, "status": "Titular" },
            { "pos": "MEI", "name": "Marquinho", "strength": 71, "status": "Titular" },
            { "pos": "ATA", "name": "Douglas Baggio", "strength": 75, "status": "Titular" },
            { "pos": "CA", "name": "Alex Sandro", "strength": 74, "status": "Titular" },
            { "pos": "GOL", "name": "Jordan", "strength": 71, "status": "Reserva" },
            { "pos": "LD", "name": "Matheus Barbosa", "strength": 72, "status": "Reserva" },
            { "pos": "CA", "name": "Leandro Pereira", "strength": 73, "status": "Reserva" }
        ]
    },
    { 
        id: 40, 
        name: "Athletic Club", 
        short: "ATH", 
        color: "#000000", 
        strength: 70, 
        serie: "B",
        roster: [
            { "pos": "GOL", "name": "Jhonatan", "strength": 71, "status": "Titular" },
            { "pos": "LD", "name": "Douglas Pelé", "strength": 69, "status": "Titular" },
            { "pos": "ZAG", "name": "Philipe Sampaio", "strength": 73, "status": "Titular" },
            { "pos": "ZAG", "name": "Sidimar", "strength": 72, "status": "Titular" },
            { "pos": "LE", "name": "Nathan", "strength": 68, "status": "Titular" },
            { "pos": "VOL", "name": "David Braga", "strength": 70, "status": "Titular" },
            { "pos": "VOL", "name": "Ian Luccas", "strength": 71, "status": "Titular" },
            { "pos": "MEI", "name": "Chico Geraldes", "strength": 75, "status": "Titular" },
            { "pos": "MEI", "name": "Gustavinho", "strength": 72, "status": "Titular" },
            { "pos": "ATA", "name": "Welinton", "strength": 71, "status": "Titular" },
            { "pos": "CA", "name": "Jonathas", "strength": 74, "status": "Titular" },
            { "pos": "GOL", "name": "Glauco", "strength": 68, "status": "Reserva" },
            { "pos": "MEI", "name": "Gian Cabezas", "strength": 69, "status": "Reserva" },
            { "pos": "CA", "name": "Denilson", "strength": 72, "status": "Reserva" }
        ]
    }
];

export default teams;
