const teams = [
    {
        "id": 1,
        "name": "Palmeiras",
        "short": "PAL",
        "color": "#006437",
        "strength": 93,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Carlos Miguel", "strength": 86, "status": "Titular" },
            { "pos": "LD", "name": "Khellven", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Gustavo Gómez", "strength": 84, "status": "Titular" },
            { "pos": "ZAG", "name": "Murilo", "strength": 86, "status": "Titular" },
            { "pos": "LE", "name": "Joaquín Piquerez", "strength": 85, "status": "Titular" },
            { "pos": "VOL", "name": "Marlon Freitas", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Andreas Pereira", "strength": 88, "status": "Titular" },
            { "pos": "MEI", "name": "Jhon Arias", "strength": 88, "status": "Titular" },
            { "pos": "MEI", "name": "Felipe Anderson", "strength": 85, "status": "Titular" },
            { "pos": "ATA", "name": "Paulinho", "strength": 88, "status": "Titular" },
            { "pos": "CA", "name": "Vitor Roque", "strength": 90, "status": "Titular" },
            { "pos": "GOL", "name": "Marcelo Lomba", "strength": 74, "status": "Reserva" },
            { "pos": "LD", "name": "Agustín Giay", "strength": 80, "status": "Reserva" },
            { "pos": "ZAG", "name": "Bruno Fuchs", "strength": 81, "status": "Reserva" },
            { "pos": "LE", "name": "Jefté", "strength": 78, "status": "Reserva" },
            { "pos": "MEI", "name": "Mauricio", "strength": 81, "status": "Reserva" },
            { "pos": "ATA", "name": "Ramón Sosa", "strength": 84, "status": "Reserva" },
            { "pos": "CA", "name": "Flaco López", "strength": 83, "status": "Reserva" },
            { "pos": "GOL", "name": "Aranha", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Luiz Benedetti", "strength": 75, "status": "Não Relacionado" },
            { "pos": "LD", "name": "Arthur Gabriel", "strength": 74, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Lucas Evangelista", "strength": 81, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Emiliano Martínez", "strength": 80, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Larson", "strength": 78, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Luighi Hanri", "strength": 79, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Riquelme", "strength": 78, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 5,
        "name": "Flamengo",
        "short": "FLA",
        "color": "#C40000",
        "strength": 96,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Agustín Rossi", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Emerson Royal", "strength": 83, "status": "Titular" },
            { "pos": "ZAG", "name": "Vitão", "strength": 85, "status": "Titular" },
            { "pos": "ZAG", "name": "Da Mata", "strength": 80, "status": "Titular" },
            { "pos": "LE", "name": "Ayrton Lucas", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Erick Pulgar", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Lucas Paquetá", "strength": 90, "status": "Titular" },
            { "pos": "MEI", "name": "Arrascaeta", "strength": 89, "status": "Titular" },
            { "pos": "MEI", "name": "Nicolás de la Cruz", "strength": 88, "status": "Titular" },
            { "pos": "ATA", "name": "Luiz Araújo", "strength": 82, "status": "Titular" },
            { "pos": "CA", "name": "Pedro", "strength": 91, "status": "Titular" },
            { "pos": "GOL", "name": "Andrew", "strength": 80, "status": "Reserva" },
            { "pos": "LD", "name": "Guillermo Varela", "strength": 78, "status": "Reserva" },
            { "pos": "ZAG", "name": "Danilo", "strength": 82, "status": "Reserva" },
            { "pos": "LE", "name": "Alex Sandro", "strength": 80, "status": "Reserva" },
            { "pos": "MEI", "name": "Saúl Ñíguez", "strength": 84, "status": "Reserva" },
            { "pos": "ATA", "name": "Gonzalo Plata", "strength": 84, "status": "Reserva" },
            { "pos": "CA", "name": "Bruno Henrique", "strength": 83, "status": "Reserva" },
            { "pos": "GOL", "name": "Dyogo Alves", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "João Victor", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Daniel Sales", "strength": 74, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Jorginho", "strength": 81, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Jorge Carrascal", "strength": 82, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Samuel Lino", "strength": 85, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Everton", "strength": 80, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Victor Hugo", "strength": 79, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 19,
        "name": "Cruzeiro",
        "short": "CRU",
        "color": "#0000CD",
        "strength": 84,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Cássio", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "William Fernando", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Zé Ivaldo", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "João Marcelo", "strength": 80, "status": "Titular" },
            { "pos": "LE", "name": "Marlon", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Walace", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Matheus Henrique", "strength": 82, "status": "Titular" },
            { "pos": "MEI", "name": "Matheus Pereira", "strength": 86, "status": "Titular" },
            { "pos": "MEI", "name": "Gerson", "strength": 83, "status": "Titular" },
            { "pos": "CA", "name": "Kaio Jorge", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Luis Sinisterra", "strength": 84, "status": "Titular" },
            { "pos": "GOL", "name": "Matheus Cunha", "strength": 78, "status": "Reserva" },
            { "pos": "LE", "name": "Kaiki", "strength": 77, "status": "Reserva" },
            { "pos": "ZAG", "name": "Lucas Villalba", "strength": 79, "status": "Reserva" },
            { "pos": "VOL", "name": "Lucas Silva", "strength": 78, "status": "Reserva" },
            { "pos": "VOL", "name": "Lucas Romero", "strength": 79, "status": "Reserva" },
            { "pos": "ATA", "name": "Bruno Rodrigues", "strength": 81, "status": "Reserva" },
            { "pos": "ATA", "name": "Marquinhos", "strength": 80, "status": "Reserva" },
            { "pos": "GOL", "name": "Marcelo", "strength": 72, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Otávio Costa", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Kauã Moraes", "strength": 73, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Jonathan Jesus", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Pedrão", "strength": 74, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Neyser Villareal", "strength": 76, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Rhuan Gabriel", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Kaique Kenji", "strength": 77, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 15,
        "name": "Botafogo",
        "short": "BOT",
        "color": "#000000",
        "strength": 88,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Raul", "strength": 80, "status": "Titular" },
            { "pos": "LD", "name": "Vitinho", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Bastos", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Alexander Barboza", "strength": 81, "status": "Titular" },
            { "pos": "LE", "name": "Alex Telles", "strength": 84, "status": "Titular" },
            { "pos": "VOL", "name": "Danilo", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Allan", "strength": 81, "status": "Titular" },
            { "pos": "MEI", "name": "Cristian Medina", "strength": 83, "status": "Titular" },
            { "pos": "ATA", "name": "Artur", "strength": 84, "status": "Titular" },
            { "pos": "ATA", "name": "Matheus Martins", "strength": 82, "status": "Titular" },
            { "pos": "CA", "name": "Arthur Cabral", "strength": 85, "status": "Titular" },
            { "pos": "GOL", "name": "Neto", "strength": 78, "status": "Reserva" },
            { "pos": "LD", "name": "Mateo Ponte", "strength": 77, "status": "Reserva" },
            { "pos": "ZAG", "name": "Nahuel Ferraresi", "strength": 80, "status": "Reserva" },
            { "pos": "ATA", "name": "Chris Ramos", "strength": 79, "status": "Reserva" },
            { "pos": "ATA", "name": "Nathan Fernandes", "strength": 81, "status": "Reserva" },
            { "pos": "ATA", "name": "Júnior Santos", "strength": 82, "status": "Reserva" },
            { "pos": "ATA", "name": "Santiago Rodríguez", "strength": 80, "status": "Reserva" },
            { "pos": "GOL", "name": "Leo Linck", "strength": 72, "status": "Não Relacionado" },
            { "pos": "LE", "name": "Fernando Marçal", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Kaio", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Gabriel Abdias", "strength": 73, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Álvaro Montoro", "strength": 75, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Miguel Caldas", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Joaquín Correa", "strength": 82, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "José Kadir", "strength": 74, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 9,
        "name": "Corinthians",
        "short": "COR",
        "color": "#FFFFFF",
        "strength": 83,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Hugo Souza", "strength": 81, "status": "Titular" },
            { "pos": "LD", "name": "Mateuzinho", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Gabriel Paulista", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "João Pedro", "strength": 81, "status": "Titular" },
            { "pos": "LE", "name": "Matheus Bidu", "strength": 76, "status": "Titular" },
            { "pos": "VOL", "name": "Raniele", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "André Carrillo", "strength": 83, "status": "Titular" },
            { "pos": "MEI", "name": "Rodrigo Garro", "strength": 86, "status": "Titular" },
            { "pos": "MEI", "name": "Breno Bidon", "strength": 84, "status": "Titular" },
            { "pos": "ATA", "name": "Memphis Depay", "strength": 90, "status": "Titular" },
            { "pos": "CA", "name": "Yuri Alberto", "strength": 84, "status": "Titular" },
            { "pos": "GOL", "name": "Felipe Longo", "strength": 75, "status": "Reserva" },
            { "pos": "LD", "name": "Pedro Milans", "strength": 78, "status": "Reserva" },
            { "pos": "LE", "name": "Fabrizio Angileri", "strength": 79, "status": "Reserva" },
            { "pos": "VOL", "name": "Allan", "strength": 81, "status": "Reserva" },
            { "pos": "MEI", "name": "Charles", "strength": 78, "status": "Reserva" },
            { "pos": "ATA", "name": "Vitinho", "strength": 78, "status": "Reserva" },
            { "pos": "CA", "name": "Pedro Raúl", "strength": 77, "status": "Reserva" },
            { "pos": "GOL", "name": "Kauê Camargo", "strength": 72, "status": "Não Relacionado" },
            { "pos": "LE", "name": "Hugo", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Jacaré", "strength": 75, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Guilherme Amorim", "strength": 74, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "André", "strength": 75, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Luiz Gustavo", "strength": 78, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Kayke Ferrari", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Zakaria Labyad", "strength": 79, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 4,
        "name": "Bahia",
        "short": "BAH",
        "color": "#0033A0",
        "strength": 85,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "João Paulo", "strength": 83, "status": "Titular" },
            { "pos": "LD", "name": "Gilberto", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Gabriel Xavier", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Kanu", "strength": 79, "status": "Titular" },
            { "pos": "LE", "name": "Camilo Cándido", "strength": 78, "status": "Titular" },
            { "pos": "VOL", "name": "Caio Alexandre", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Jean Lucas", "strength": 82, "status": "Titular" },
            { "pos": "MEI", "name": "Everton Ribeiro", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "Rodrigo Nestor", "strength": 82, "status": "Titular" },
            { "pos": "ATA", "name": "Luciano Juba", "strength": 81, "status": "Titular" },
            { "pos": "CA", "name": "Willian José", "strength": 84, "status": "Titular" },
            { "pos": "GOL", "name": "Ronaldo", "strength": 78, "status": "Reserva" },
            { "pos": "LD", "name": "Santiago Ramos", "strength": 77, "status": "Reserva" },
            { "pos": "ZAG", "name": "Vitor Hugo", "strength": 78, "status": "Reserva" },
            { "pos": "LE", "name": "Iago", "strength": 80, "status": "Reserva" },
            { "pos": "MEI", "name": "Cauly", "strength": 83, "status": "Reserva" },
            { "pos": "ATA", "name": "Ademir", "strength": 80, "status": "Reserva" },
            { "pos": "CA", "name": "Everaldo", "strength": 79, "status": "Reserva" },
            { "pos": "GOL", "name": "Victor", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "David Duarte", "strength": 76, "status": "Não Relacionado" },
            { "pos": "LD", "name": "Román Gómez", "strength": 75, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Nicolás Acevedo", "strength": 80, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Michel Araújo", "strength": 78, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Erick Pulga", "strength": 81, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Mateo Sanabria", "strength": 78, "status": "Não Relacionado" },
            { "pos": "CA", "name": "Cristian Olivera", "strength": 80, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 3,
        "name": "Fluminense",
        "short": "FLU",
        "color": "#8A1538",
        "strength": 84,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Fábio", "strength": 82, "status": "Titular" },
            { "pos": "LD", "name": "Samuel Xavier", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Thiago Silva", "strength": 85, "status": "Titular" },
            { "pos": "ZAG", "name": "Ignácio", "strength": 81, "status": "Titular" },
            { "pos": "LE", "name": "Guilherme Arana", "strength": 86, "status": "Titular" },
            { "pos": "VOL", "name": "Facundo Bernal", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Martinelli", "strength": 81, "status": "Titular" },
            { "pos": "MEI", "name": "Ganso", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "David Terans", "strength": 80, "status": "Titular" },
            { "pos": "ATA", "name": "Jefferson Savarino", "strength": 85, "status": "Titular" },
            { "pos": "CA", "name": "Germán Cano", "strength": 83, "status": "Titular" },
            { "pos": "GOL", "name": "Marcelo Pitaluga", "strength": 76, "status": "Reserva" },
            { "pos": "LD", "name": "Guga", "strength": 78, "status": "Reserva" },
            { "pos": "ZAG", "name": "Igor Rabello", "strength": 79, "status": "Reserva" },
            { "pos": "LE", "name": "Gabriel Fuentes", "strength": 80, "status": "Reserva" },
            { "pos": "MEI", "name": "Luciano Acosta", "strength": 85, "status": "Reserva" },
            { "pos": "ATA", "name": "Yeferson Soteldo", "strength": 82, "status": "Reserva" },
            { "pos": "CA", "name": "John Kennedy", "strength": 81, "status": "Reserva" },
            { "pos": "GOL", "name": "Vitor Eudes", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Juan Freytes", "strength": 77, "status": "Não Relacionado" },
            { "pos": "LE", "name": "René", "strength": 78, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Nonato", "strength": 77, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Hércules", "strength": 81, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Kevin Serna", "strength": 80, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Agustín Canobbio", "strength": 82, "status": "Não Relacionado" },
            { "pos": "CA", "name": "Matheus Reis", "strength": 79, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 7,
        "name": "Grêmio",
        "short": "GRE",
        "color": "#0099FF",
        "strength": 82,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Weverton", "strength": 86, "status": "Titular" },
            { "pos": "LD", "name": "Joao Pedro", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Wagner Leonardo", "strength": 83, "status": "Titular" },
            { "pos": "ZAG", "name": "Wálter Kannemann", "strength": 82, "status": "Titular" },
            { "pos": "LE", "name": "Caio Paulista", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Mathías Villasanti", "strength": 85, "status": "Titular" },
            { "pos": "VOL", "name": "Dodi", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Franco Cristaldo", "strength": 84, "status": "Titular" },
            { "pos": "MEI", "name": "Miguel Monsalve", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Soteldo", "strength": 85, "status": "Titular" },
            { "pos": "CA", "name": "Martin Braithwaite", "strength": 84, "status": "Titular" },
            { "pos": "GOL", "name": "Gabriel Grando", "strength": 78, "status": "Reserva" },
            { "pos": "LD", "name": "Pedro Gabriel", "strength": 76, "status": "Reserva" },
            { "pos": "ZAG", "name": "Fabián Balbuena", "strength": 81, "status": "Reserva" },
            { "pos": "ZAG", "name": "Gustavo Martins", "strength": 79, "status": "Reserva" },
            { "pos": "VOL", "name": "Arthur", "strength": 82, "status": "Reserva" },
            { "pos": "ATA", "name": "Cristian Pavón", "strength": 82, "status": "Reserva" },
            { "pos": "CA", "name": "Carlos Vinícius", "strength": 81, "status": "Reserva" },
            { "pos": "GOL", "name": "Thiago Stallbaum", "strength": 72, "status": "Não Relacionado" },
            { "pos": "LE", "name": "Marlon", "strength": 79, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Luis Eduardo", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Athos Thawan", "strength": 75, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Juan Nardoni", "strength": 75, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Leonel Pérez", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Francis Amuzu", "strength": 78, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Mateus Tetê", "strength": 80, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 8,
        "name": "Athletico-PR",
        "short": "CAP",
        "color": "#D80027",
        "strength": 88,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Mycael", "strength": 82, "status": "Titular" },
            { "pos": "LD", "name": "Dudu", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Carlos Terán", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Habraão", "strength": 79, "status": "Titular" },
            { "pos": "LE", "name": "Lucas Esquivel", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Juan Portilla", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Alejandro García", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Bruno Zapelli", "strength": 85, "status": "Titular" },
            { "pos": "MEI", "name": "João Cruz", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Julimar", "strength": 82, "status": "Titular" },
            { "pos": "CA", "name": "Stiven Mendoza", "strength": 84, "status": "Titular" },
            { "pos": "GOL", "name": "Santos", "strength": 81, "status": "Reserva" },
            { "pos": "LD", "name": "Claudinho", "strength": 78, "status": "Reserva" },
            { "pos": "ZAG", "name": "Gustavo Veiga", "strength": 77, "status": "Reserva" },
            { "pos": "VOL", "name": "Daniel Aguilar", "strength": 78, "status": "Reserva" },
            { "pos": "MEI", "name": "Luiz Gustavo", "strength": 80, "status": "Reserva" },
            { "pos": "ATA", "name": "Lucas Amorim", "strength": 78, "status": "Reserva" },
            { "pos": "CA", "name": "Kevin Viveros", "strength": 79, "status": "Reserva" },
            { "pos": "GOL", "name": "Matheus Rocha", "strength": 72, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Maksym Voronov", "strength": 72, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Carlos Eduardo", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Murilo Camargo", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Gilberto Junior", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Léo", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Filipinho", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Sorriso", "strength": 79, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 10,
        "name": "Vasco",
        "short": "VAS",
        "color": "#000000",
        "strength": 82,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Léo Jardim", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Paulo Henrique", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Alan Saldivia", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Carlos Cuesta", "strength": 81, "status": "Titular" },
            { "pos": "LE", "name": "Cuiabano", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Hugo Moura", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Matheus Carvalho", "strength": 79, "status": "Titular" },
            { "pos": "MEI", "name": "Nuno Moreira", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Adson", "strength": 82, "status": "Titular" },
            { "pos": "ATA", "name": "David", "strength": 80, "status": "Titular" },
            { "pos": "CA", "name": "Claudio Spinelli", "strength": 81, "status": "Titular" },
            { "pos": "GOL", "name": "Daniel Fuzato", "strength": 78, "status": "Reserva" },
            { "pos": "LD", "name": "José Luis Rodríguez", "strength": 78, "status": "Reserva" },
            { "pos": "ZAG", "name": "Walace", "strength": 80, "status": "Reserva" },
            { "pos": "ZAG", "name": "Lucas Freitas", "strength": 76, "status": "Reserva" },
            { "pos": "VOL", "name": "Jair", "strength": 81, "status": "Reserva" },
            { "pos": "MEI", "name": "Thiago Mendes", "strength": 80, "status": "Reserva" },
            { "pos": "ATA", "name": "Matheus França", "strength": 81, "status": "Reserva" },
            { "pos": "GOL", "name": "Allan", "strength": 74, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Pablo", "strength": 72, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Tchê Tchê", "strength": 79, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Cauan Barros", "strength": 75, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "JP", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Andres Gomez", "strength": 78, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Marino Hinestroza", "strength": 77, "status": "Não Relacionado" },
            { "pos": "CA", "name": "Brenner", "strength": 76, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 11,
        "name": "Atlético-MG",
        "short": "CAM",
        "color": "#000000",
        "strength": 84,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Éverson", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Mariano", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Júnior Alonso", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Lyanco", "strength": 81, "status": "Titular" },
            { "pos": "LE", "name": "Natanael", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Rodrigo Battaglia", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Alan Franco", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Zaracho", "strength": 82, "status": "Titular" },
            { "pos": "MEI", "name": "Mateus Iseppe", "strength": 84, "status": "Titular" },
            { "pos": "ATA", "name": "Hulk", "strength": 86, "status": "Titular" },
            { "pos": "CA", "name": "Mateo Casierra", "strength": 85, "status": "Titular" },
            { "pos": "GOL", "name": "Gabriel Delfim", "strength": 76, "status": "Reserva" },
            { "pos": "LD", "name": "Vitinho", "strength": 75, "status": "Reserva" },
            { "pos": "ZAG", "name": "Iván Román", "strength": 78, "status": "Reserva" },
            { "pos": "ZAG", "name": "Ruan", "strength": 77, "status": "Reserva" },
            { "pos": "MEI", "name": "Mamady Cissé", "strength": 78, "status": "Reserva" },
            { "pos": "ATA", "name": "Alan Minda", "strength": 81, "status": "Reserva" },
            { "pos": "ATA", "name": "Tomás Cuello", "strength": 80, "status": "Reserva" },
            { "pos": "GOL", "name": "Pedro Cobra", "strength": 72, "status": "Não Relacionado" },
            { "pos": "LD", "name": "Rômulo", "strength": 75, "status": "Não Relacionado" },
            { "pos": "LE", "name": "Rubens", "strength": 79, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Allan", "strength": 81, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Victor Hugo", "strength": 79, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Igor Toledo", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Murillo Fernandes", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Dudu", "strength": 74, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 12,
        "name": "Bragantino",
        "short": "RBB",
        "color": "#FFFFFF",
        "strength": 82,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Cleiton", "strength": 82, "status": "Titular" },
            { "pos": "LD", "name": "José Hurtado", "strength": 80, "status": "Titular" },
            { "pos": "ZAG", "name": "Alix Vinicius", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Pedro Henrique", "strength": 80, "status": "Titular" },
            { "pos": "LE", "name": "Juninho Capixaba", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Ramires", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Matheus Fernandes", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Barbosa", "strength": 82, "status": "Titular" },
            { "pos": "MEI", "name": "Rodriguinho", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Henry Mosquera", "strength": 80, "status": "Titular" },
            { "pos": "CA", "name": "Isidro Pitta", "strength": 83, "status": "Titular" },
            { "pos": "GOL", "name": "Tiago Volpi", "strength": 79, "status": "Reserva" },
            { "pos": "LD", "name": "Agustín Sant'Anna", "strength": 78, "status": "Reserva" },
            { "pos": "ZAG", "name": "Gustavo Marques", "strength": 78, "status": "Reserva" },
            { "pos": "LE", "name": "Vanderlan", "strength": 80, "status": "Reserva" },
            { "pos": "VOL", "name": "Fabinho", "strength": 78, "status": "Reserva" },
            { "pos": "MEI", "name": "Gustavinho", "strength": 77, "status": "Reserva" },
            { "pos": "CA", "name": "Eduardo Sasha", "strength": 81, "status": "Reserva" },
            { "pos": "GOL", "name": "Fernando Costa", "strength": 72, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Fabrício", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Weimar Vivas", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Caue Nascimento", "strength": 75, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Ignacio Sosa", "strength": 76, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Bruno Conceicão", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Fernando", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Vinicinho", "strength": 76, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 13,
        "name": "Vitória",
        "short": "VIT",
        "color": "#D80027",
        "strength": 77,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Lucas Arcanjo", "strength": 80, "status": "Titular" },
            { "pos": "LD", "name": "Nathan", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Camutanga", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Riccieli", "strength": 80, "status": "Titular" },
            { "pos": "LE", "name": "Luan Cândido", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Ronald", "strength": 79, "status": "Titular" },
            { "pos": "VOL", "name": "Gabriel Baralhas", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Matheusinho", "strength": 82, "status": "Titular" },
            { "pos": "ATA", "name": "Marinho", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Osvaldo", "strength": 79, "status": "Titular" },
            { "pos": "CA", "name": "Renato Kayzer", "strength": 81, "status": "Titular" },
            { "pos": "GOL", "name": "Ezequiel", "strength": 77, "status": "Reserva" },
            { "pos": "LD", "name": "Diego Tarzia", "strength": 75, "status": "Reserva" },
            { "pos": "ZAG", "name": "Claudinho", "strength": 78, "status": "Reserva" },
            { "pos": "ZAG", "name": "Ramon", "strength": 77, "status": "Reserva" },
            { "pos": "VOL", "name": "Emmanuel Martínez", "strength": 79, "status": "Reserva" },
            { "pos": "MEI", "name": "Edenilson", "strength": 81, "status": "Reserva" },
            { "pos": "CA", "name": "Renzo López", "strength": 78, "status": "Reserva" },
            { "pos": "GOL", "name": "Gabriel", "strength": 74, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Fintelman", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Cacá", "strength": 79, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Edu", "strength": 76, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Dudu", "strength": 77, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Enrique Saverio", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Aitor Cantalapiedra", "strength": 78, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Luis Miguel", "strength": 75, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 14,
        "name": "Chapecoense",
        "short": "CHA",
        "color": "#00913F",
        "strength": 75,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Wellington", "strength": 80, "status": "Titular" },
            { "pos": "LD", "name": "Gustavo Talles", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Eduardo Doma", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "João Paulo", "strength": 78, "status": "Titular" },
            { "pos": "LE", "name": "Mancha", "strength": 76, "status": "Titular" },
            { "pos": "VOL", "name": "Bruno Matias", "strength": 78, "status": "Titular" },
            { "pos": "VOL", "name": "Vinicius", "strength": 77, "status": "Titular" },
            { "pos": "MEI", "name": "Giovanni Augusto", "strength": 82, "status": "Titular" },
            { "pos": "ATA", "name": "Marcinho", "strength": 79, "status": "Titular" },
            { "pos": "ATA", "name": "Yannick Bolasie", "strength": 84, "status": "Titular" },
            { "pos": "CA", "name": "Pedro Perotti", "strength": 81, "status": "Titular" },
            { "pos": "GOL", "name": "Rafael Santos", "strength": 76, "status": "Reserva" },
            { "pos": "LD", "name": "Marcos Vinicius", "strength": 75, "status": "Reserva" },
            { "pos": "ZAG", "name": "Rafael Thyere", "strength": 80, "status": "Reserva" },
            { "pos": "LE", "name": "Walter Clar", "strength": 77, "status": "Reserva" },
            { "pos": "VOL", "name": "Jean", "strength": 76, "status": "Reserva" },
            { "pos": "MEI", "name": "Higor Meritão", "strength": 78, "status": "Reserva" },
            { "pos": "CA", "name": "Jonathan Palacios", "strength": 77, "status": "Reserva" },
            { "pos": "GOL", "name": "Léo", "strength": 72, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Kainã", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Kauan", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Victor Caetano", "strength": 73, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Everton", "strength": 75, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Camilo", "strength": 78, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Ênio", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Neto", "strength": 75, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 16,
        "name": "Mirassol",
        "short": "MIR",
        "color": "#FFD700",
        "strength": 82,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Walter", "strength": 81, "status": "Titular" },
            { "pos": "LD", "name": "Lucas Oliveira", "strength": 75, "status": "Titular" },
            { "pos": "ZAG", "name": "Willian Machado", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Henri", "strength": 77, "status": "Titular" },
            { "pos": "LE", "name": "Zeca", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Yuri", "strength": 78, "status": "Titular" },
            { "pos": "VOL", "name": "Shaylon", "strength": 82, "status": "Titular" },
            { "pos": "MEI", "name": "Chico", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Tiquinho Soares", "strength": 84, "status": "Titular" },
            { "pos": "ATA", "name": "Nathan Fogaça", "strength": 79, "status": "Titular" },
            { "pos": "CA", "name": "André Luis", "strength": 81, "status": "Titular" },
            { "pos": "GOL", "name": "Alex Muralha", "strength": 78, "status": "Reserva" },
            { "pos": "LD", "name": "Reinaldo", "strength": 76, "status": "Reserva" },
            { "pos": "ZAG", "name": "Zé Carlos", "strength": 77, "status": "Reserva" },
            { "pos": "VOL", "name": "Neto Moura", "strength": 79, "status": "Reserva" },
            { "pos": "MEI", "name": "Lucas Mugni", "strength": 80, "status": "Reserva" },
            { "pos": "ATA", "name": "Negueba", "strength": 78, "status": "Reserva" },
            { "pos": "ATA", "name": "Everton", "strength": 79, "status": "Reserva" },
            { "pos": "GOL", "name": "Thomazella", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Luiz Gustavo", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Gazal", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Bruno Santos", "strength": 74, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Denilson", "strength": 78, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "José Aldo", "strength": 77, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Carlos Eduardo", "strength": 78, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Antonio Galeano", "strength": 78, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 17,
        "name": "Santos",
        "short": "SAN",
        "color": "#FFFFFF",
        "strength": 82,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Gabriel Brazão", "strength": 99, "status": "Titular" },
            { "pos": "LD", "name": "Mayke", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Lucas Verissimo", "strength": 84, "status": "Titular" },
            { "pos": "ZAG", "name": "Luan Peres", "strength": 81, "status": "Titular" },
            { "pos": "LE", "name": "Gonzalo Escobar", "strength": 79, "status": "Titular" },
            { "pos": "VOL", "name": "João Schmidt", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Zé Rafael", "strength": 82, "status": "Titular" },
            { "pos": "MEI", "name": "Neymar", "strength": 91, "status": "Titular" },
            { "pos": "ATA", "name": "Gabriel Barbosa", "strength": 86, "status": "Titular" },
            { "pos": "ATA", "name": "Rony", "strength": 83, "status": "Titular" },
            { "pos": "CA", "name": "Lautaro Díaz", "strength": 82, "status": "Titular" },
            { "pos": "GOL", "name": "Diogenes", "strength": 75, "status": "Reserva" },
            { "pos": "LD", "name": "Vinicius Lira", "strength": 74, "status": "Reserva" },
            { "pos": "ZAG", "name": "Joao Basso", "strength": 79, "status": "Reserva" },
            { "pos": "VOL", "name": "Willian Arão", "strength": 81, "status": "Reserva" },
            { "pos": "MEI", "name": "Thaciano", "strength": 80, "status": "Reserva" },
            { "pos": "ATA", "name": "Moisés", "strength": 81, "status": "Reserva" },
            { "pos": "ATA", "name": "Benjamín Rollheiser", "strength": 80, "status": "Reserva" },
            { "pos": "GOL", "name": "João Pedro", "strength": 72, "status": "Não Relacionado" },
            { "pos": "LD", "name": "Igor", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "João Ananias", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Zé Ivaldo", "strength": 78, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Pepê Fermino", "strength": 75, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Álvaro Barreal", "strength": 81, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Gabriel Menino", "strength": 80, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Miguel Terceros", "strength": 78, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 18,
        "name": "Internacional",
        "short": "INT",
        "color": "#E50000",
        "strength": 83,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Sergio Rochet", "strength": 84, "status": "Titular" },
            { "pos": "LD", "name": "Matheus Bahia", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Félix Torres", "strength": 82, "status": "Titular" },
            { "pos": "ZAG", "name": "Gabriel Mercado", "strength": 79, "status": "Titular" },
            { "pos": "LE", "name": "Alexander Bernabei", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Thiago Maia", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Bruno Gomes", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Alan Patrick", "strength": 85, "status": "Titular" },
            { "pos": "MEI", "name": "Bruno Tabata", "strength": 81, "status": "Titular" },
            { "pos": "ATA", "name": "Johan Carbonero", "strength": 82, "status": "Titular" },
            { "pos": "CA", "name": "Rafael Borré", "strength": 84, "status": "Titular" },
            { "pos": "GOL", "name": "Kauan", "strength": 75, "status": "Reserva" },
            { "pos": "LD", "name": "Lázaro", "strength": 76, "status": "Reserva" },
            { "pos": "ZAG", "name": "Alisson", "strength": 78, "status": "Reserva" },
            { "pos": "VOL", "name": "Rodrigo Villagra", "strength": 80, "status": "Reserva" },
            { "pos": "MEI", "name": "Paulinho", "strength": 79, "status": "Reserva" },
            { "pos": "CA", "name": "Alerrandro", "strength": 81, "status": "Reserva" },
            { "pos": "ATA", "name": "Kayky Chagas", "strength": 80, "status": "Reserva" },
            { "pos": "GOL", "name": "Anthoni", "strength": 72, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Diego Esser", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Victor Gabriel", "strength": 73, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Denis Marfo", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Pedro Kauã", "strength": 74, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Bruno Henrique", "strength": 78, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Alan Rodríguez", "strength": 77, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Richard", "strength": 76, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 6,
        "name": "Coritiba",
        "short": "CFC",
        "color": "#006437",
        "strength": 79,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Pedro Luccas", "strength": 82, "status": "Titular" },
            { "pos": "LD", "name": "João Pedro Chermont", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Maicon", "strength": 80, "status": "Titular" },
            { "pos": "ZAG", "name": "Rodrigo Moledo", "strength": 79, "status": "Titular" },
            { "pos": "LE", "name": "Felipe Jonatan", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Sebastián Gómez", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Fernando Sobral", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Josué Pesqueira", "strength": 81, "status": "Titular" },
            { "pos": "MEI", "name": "Thiago Santos", "strength": 79, "status": "Titular" },
            { "pos": "ATA", "name": "Lucas Ronier", "strength": 81, "status": "Titular" },
            { "pos": "CA", "name": "Keno", "strength": 83, "status": "Titular" },
            { "pos": "GOL", "name": "Pedro Rangel", "strength": 78, "status": "Reserva" },
            { "pos": "LD", "name": "Jacy Maranhão", "strength": 77, "status": "Reserva" },
            { "pos": "ZAG", "name": "Bruno Melo", "strength": 78, "status": "Reserva" },
            { "pos": "ZAG", "name": "Tiago", "strength": 77, "status": "Reserva" },
            { "pos": "MEI", "name": "Thiago Azaf", "strength": 76, "status": "Reserva" },
            { "pos": "ATA", "name": "Joaquín Lavega", "strength": 78, "status": "Reserva" },
            { "pos": "CA", "name": "Enzo Vágner", "strength": 77, "status": "Reserva" },
            { "pos": "GOL", "name": "Keiller", "strength": 76, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Benassi", "strength": 75, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Gabriel Leite", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "João Almeida", "strength": 75, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Felipe Guimarães Da Silva", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Lucas Taverna", "strength": 73, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Miguel Silva", "strength": 74, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Brayan", "strength": 75, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 20,
        "name": "Remo",
        "short": "REM",
        "color": "#0B173B",
        "strength": 74,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Ivan", "strength": 80, "status": "Titular" },
            { "pos": "LD", "name": "Cristian Tassano", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Thalisson Gabriel", "strength": 79, "status": "Titular" },
            { "pos": "ZAG", "name": "Klaus", "strength": 78, "status": "Titular" },
            { "pos": "LE", "name": "Braian Cufré", "strength": 80, "status": "Titular" },
            { "pos": "VOL", "name": "Patrick de Paula", "strength": 81, "status": "Titular" },
            { "pos": "VOL", "name": "Victor Cantillo", "strength": 80, "status": "Titular" },
            { "pos": "MEI", "name": "Yago Pikachu", "strength": 82, "status": "Titular" },
            { "pos": "ATA", "name": "Carlinhos", "strength": 79, "status": "Titular" },
            { "pos": "ATA", "name": "Alef Manga", "strength": 83, "status": "Titular" },
            { "pos": "CA", "name": "Gabriel Poveda", "strength": 81, "status": "Titular" },
            { "pos": "GOL", "name": "João Victor", "strength": 75, "status": "Reserva" },
            { "pos": "LD", "name": "Marcelinho", "strength": 76, "status": "Reserva" },
            { "pos": "ZAG", "name": "Léo Andrade", "strength": 78, "status": "Reserva" },
            { "pos": "VOL", "name": "Nathan", "strength": 77, "status": "Reserva" },
            { "pos": "MEI", "name": "Giovanni Confreste", "strength": 76, "status": "Reserva" },
            { "pos": "ATA", "name": "Jaderson", "strength": 78, "status": "Reserva" },
            { "pos": "MEI", "name": "Vitor Bueno", "strength": 80, "status": "Reserva" },
            { "pos": "GOL", "name": "Marcelo Rangel", "strength": 72, "status": "Não Relacionado" },
            { "pos": "GOL", "name": "Ygor Vinhas", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Duplexe Tchamba", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Marllon", "strength": 77, "status": "Não Relacionado" },
            { "pos": "LD", "name": "Savio", "strength": 75, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Leonel Picco", "strength": 76, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Franco Catarozzi", "strength": 74, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Zé Ricardo", "strength": 75, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 2,
        "name": "São Paulo",
        "short": "SAO",
        "color": "#FE0000",
        "strength": 83,
        "serie": "A",
        "roster": [
            { "pos": "GOL", "name": "Rafael", "strength": 82, "status": "Titular" },
            { "pos": "LD", "name": "Lucas Ramon", "strength": 78, "status": "Titular" },
            { "pos": "ZAG", "name": "Arboleda", "strength": 81, "status": "Titular" },
            { "pos": "ZAG", "name": "Alan Franco", "strength": 80, "status": "Titular" },
            { "pos": "LE", "name": "Wendell", "strength": 83, "status": "Titular" },
            { "pos": "VOL", "name": "Marcos Antonio", "strength": 82, "status": "Titular" },
            { "pos": "VOL", "name": "Pablo Maia", "strength": 85, "status": "Titular" },
            { "pos": "MEI", "name": "Lucas Moura", "strength": 86, "status": "Titular" },
            { "pos": "MEI", "name": "Cauly", "strength": 84, "status": "Titular" },
            { "pos": "ATA", "name": "Ferreira", "strength": 81, "status": "Titular" },
            { "pos": "CA", "name": "Calleri", "strength": 84, "status": "Titular" },
            { "pos": "GOL", "name": "Carlos Coronel", "strength": 80, "status": "Reserva" },
            { "pos": "LD", "name": "Igor Felisberto", "strength": 75, "status": "Reserva" },
            { "pos": "ZAG", "name": "Rafael Tolói", "strength": 81, "status": "Reserva" },
            { "pos": "LE", "name": "Hugo", "strength": 77, "status": "Reserva" },
            { "pos": "VOL", "name": "Damián Bobadilla", "strength": 80, "status": "Reserva" },
            { "pos": "MEI", "name": "Luciano", "strength": 82, "status": "Reserva" },
            { "pos": "CA", "name": "André Silva", "strength": 80, "status": "Reserva" },
            { "pos": "GOL", "name": "Young", "strength": 72, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Sabino", "strength": 76, "status": "Não Relacionado" },
            { "pos": "ZAG", "name": "Dória", "strength": 80, "status": "Não Relacionado" },
            { "pos": "VOL", "name": "Luan", "strength": 78, "status": "Não Relacionado" },
            { "pos": "MEI", "name": "Danielzinho", "strength": 79, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Gonzalo Tapia", "strength": 82, "status": "Não Relacionado" },
            { "pos": "ATA", "name": "Tetê", "strength": 83, "status": "Não Relacionado" },
            { "pos": "CA", "name": "Paulo Sérgio", "strength": 78, "status": "Não Relacionado" }
        ]
    },
    {
        "id": 21,
        "name": "Fortaleza",
        "short": "FOR",
        "color": "#174594",
        "strength": 84,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 75, "status": "Reserva" })
    },
    {
        "id": 22,
        "name": "Ceará",
        "short": "CEA",
        "color": "#000000",
        "strength": 79,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 74, "status": "Reserva" })
    },
    {
        "id": 23,
        "name": "Sport",
        "short": "SPT",
        "color": "#D2151E",
        "strength": 77,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 73, "status": "Reserva" })
    },
    {
        "id": 24,
        "name": "Goiás",
        "short": "GOI",
        "color": "#006437",
        "strength": 77,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 73, "status": "Reserva" })
    },
    {
        "id": 25,
        "name": "Cuiabá",
        "short": "CUI",
        "color": "#006437",
        "strength": 78,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 72, "status": "Reserva" })
    },
    {
        "id": 26,
        "name": "Juventude",
        "short": "JUV",
        "color": "#008000",
        "strength": 75,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 72, "status": "Reserva" })
    },
    {
        "id": 27,
        "name": "Atlético-GO",
        "short": "ACG",
        "color": "#E30613",
        "strength": 74,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 71, "status": "Reserva" })
    },
    {
        "id": 28,
        "name": "Criciúma",
        "short": "CRI",
        "color": "#F7E01A",
        "strength": 76,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 72, "status": "Reserva" })
    },
    {
        "id": 29,
        "name": "Novorizontino",
        "short": "NOV",
        "color": "#FFFF00",
        "strength": 74,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 71, "status": "Reserva" })
    },
    {
        "id": 30,
        "name": "América-MG",
        "short": "AMG",
        "color": "#008000",
        "strength": 75,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 72, "status": "Reserva" })
    },
    {
        "id": 31,
        "name": "Avaí",
        "short": "AVA",
        "color": "#0067B1",
        "strength": 73,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 70, "status": "Reserva" })
    },
    {
        "id": 32,
        "name": "CRB",
        "short": "CRB",
        "color": "#FF0000",
        "strength": 72,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 70, "status": "Reserva" })
    },
    {
        "id": 33,
        "name": "Vila Nova",
        "short": "VIL",
        "color": "#FF0000",
        "strength": 75,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 71, "status": "Reserva" })
    },
    {
        "id": 34,
        "name": "Ponte Preta",
        "short": "PON",
        "color": "#FFFFFF",
        "strength": 73,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 69, "status": "Reserva" })
    },
    {
        "id": 35,
        "name": "Operário-PR",
        "short": "OPE",
        "color": "#000000",
        "strength": 76,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 71, "status": "Reserva" })
    },
    {
        "id": 36,
        "name": "Londrina",
        "short": "LEC",
        "color": "#00AEEF",
        "strength": 68,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 66, "status": "Reserva" })
    },
    {
        "id": 37,
        "name": "Brusque",
        "short": "BRU",
        "color": "#FFFF00",
        "strength": 67,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 65, "status": "Reserva" })
    },
    {
        "id": 38,
        "name": "Guarani",
        "short": "GUA",
        "color": "#006437",
        "strength": 66,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 64, "status": "Reserva" })
    },
    {
        "id": 39,
        "name": "Botafogo-SP",
        "short": "BSP",
        "color": "#FF0000",
        "strength": 72,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 68, "status": "Reserva" })
    },
    {
        "id": 40,
        "name": "Athletic Club",
        "short": "ATH",
        "color": "#000000",
        "strength": 70,
        "serie": "B",
        "roster": Array(26).fill({ "pos": "CA", "name": "Generic Player", "strength": 67, "status": "Reserva" })
    }
];

export default teams;
